name: Queue Runner

on:
  # 手动触发工作流
  workflow_dispatch:
  # 通过 API 以特定类型触发工作流
  repository_dispatch:
    types: [expand-and-run]

jobs:
  expand-and-run:
    runs-on: ubuntu-24.04
    steps:
      # 显示系统信息，如 CPU、内存、磁盘等
      - name: Show system info
        run: |
          lscpu
          free -h
          df -Th
          uname -a

      # 创建工作目录并设置环境变量
      - name: Set working directory
        run: |
          sudo mkdir -p /builder
          sudo chown -R runner:runner /builder
          echo "WORKDIR=/builder" >> $GITHUB_ENV

      # 释放磁盘空间，删除不必要的文件和服务
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo docker image prune -a -f
          sudo systemctl stop docker
          sudo snap set system refresh.retain=2
          sudo apt-get -y purge firefox clang* gcc-12 gcc-14 ghc* google* llvm* mono* mongo* mysql* php*
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          sudo rm -rf /etc/mysql /etc/php /usr/libexec/docker /usr/local /usr/src/* /var/lib/docker /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm} /usr/libexec/gcc/x86_64-linux-gnu/14 /home/linuxbrew
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          rm -rf ~/{.cargo,.dotnet,.rustup}
          df -Th

      # 创建 8GB 交换文件并启用
      - name: Create swap space
        run: |
          sudo dd if=/dev/zero of=/mnt/swapfile bs=1M count=8192
          sudo chmod 600 /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
          free -h | grep -i swap

      # 创建逻辑卷和逻辑卷组
      - name: Create VG & LV
        run: |
          mnt_size=$(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//')
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 2)
          sudo truncate -s "$mnt_size"G /mnt/mnt.img
          sudo truncate -s "$root_size"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner

      # 挂载逻辑卷到工作目录
      - name: Mount LV
        run: |
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th

      - name: Install Tools
        run: |
          sudo apt-get install -y ffmpeg
      - name: Check version
        run: ffmpeg -version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start task queue system
        env:
          QUEUE_URL: ${{ secrets.QUEUE_URL }}
        run: |
            python main.py
